import next from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from '../components/navbar';

const inputform = () => {
    return(
    <>
    <Head>
        <title>Inputform</title>
        <meta name="description" content="Generated by create next app" />
        <link href='https://fonts.googleapis.com/css?family=Work Sans' rel='stylesheet'></link>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />
      </Head>
      <Script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
crossorigin="anonymous"/>
     <Navbar />
     <form>
  <div className={styles.form-row}>
    <div className={styles.form-group} col-md-6>
      <label for="inputEmail4">Email</label>
      <input type="email" className={styles.form-control} id="inputEmail4" placeholder="Email"/>
    </div>
    <div className={styles.form-group} col-md-6>
      <label for="inputPassword4">Password</label>
      <input type="password" className={styles.form-control} id="inputPassword4" placeholder="Password"/>
    </div>
  </div>
  <div className={styles.form-group}>
    <label for="inputAddress">Address</label>
    <input type="text" className={styles.form-control} id="inputAddress" placeholder="1234 Main St"/>
  </div>
  <div className={styles.form-group}>
    <label for="inputAddress2">Address 2</label>
    <input type="text" className={styles.form-control} id="inputAddress2" placeholder="Apartment, studio, or floor"/>
  </div>
  <div className={styles.form-group}>
    <div className={styles.form-group} col-md-6>
      <label for="inputCity">City</label>
      <input type="text" className={styles.form-control} id="inputCity"/>
    </div>
    <div className={styles.form-group} col-md-4>
      <label for="inputState">State</label>
      <select id="inputState" className={styles.form-control}>
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div className={styles.form-group} col-md-2>
      <label for="inputZip">Zip</label>
      <input type="text" className={styles.form-control} id="inputZip"/>
    </div>
  </div>
  <div className={styles.form-group}>
    <div className={styles.form-check}>
      <input className={styles.form-check-input} type="checkbox" id="gridCheck"/>
      <label className={styles.form-check-label} for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" className={styles.btn} btn-primary>Sign in</button>
</form>
</>


    );
    }

    export default inputform;