import next from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Track.module.css';
import Navbar from '../components/navbar';

const track = () => {
    return(
    <><>
            <Head>
                <title>track</title>
                <meta name="description" content="Generated by create next app" />
                <link href='https://fonts.googleapis.com/css?family=Work Sans' rel='stylesheet'></link>
            </Head>

            <Navbar />
            <div className={styles.web3description}>
                <div className={styles.oneliner} id="track1">Track 1</div>
                <div className={styles.web3heading}>
                    Web3 for South Florida<br></br>Social Impact
                </div>
                <div className={styles.web3para}>
                    Have Hacker work on South Florida specific
                    solutions and help<br></br> empower the region
                </div>

            </div>

        </><div className={styles.web3}>

                <div className={styles.blockchaindescription}>
                    <div className={styles.oneliner}>Track 2</div>
                    <div className={styles.web3heading}>
                        Blockchain Gaming
                    </div>
                    <div className={styles.web3para}>
                        Blockchain gaming and play to earn is primed to
                        be the next major<br></br> wave in the web3 space, take advantage and show case your project
                    </div>

                </div>

                <div className={styles.blockchaingamingimage}>
                    <img src="/blockchaingaming.png"></img>
                </div>

            </div><div className={styles.web3}>
                <div className={styles.web3image}>
                    <img src="/fintechimage.png"></img>
                </div>

                <div className={styles.web3description1}>
                    <div className={styles.oneliner}>Track 1</div>
                    <div className={styles.web3heading}>
                        Fintech & Analysis
                    </div>
                    <div className={styles.web3para}>
                        Bring developers, analysts, and designers
                        together to build financial<br></br> projects
                    </div>

                </div>

            </div></>

    );
    }

    export default track;